const REQUEST_DATA_TICKETS = 'REQUEST_DATA_TICKETS'
const SUCCESS_DATA_TICKETS = 'SUCCESS_DATA_TICKETS'
const ERROR_REQUEST = 'ERROR_REQUEST'

export { REQUEST_DATA_TICKETS, SUCCESS_DATA_TICKETS, ERROR_REQUEST }
